---
title: "はじめまして"
author: admin
date: 2018-05-18T00:00:00Z
categories: []
tags: []
draft : false
featured: false
image:
  caption: ''
  focal_point: ""
  placement: 2
  preview_only: false
lastmod: ""
projects: []
summary: どうもはじめまして。このブログを始めるに当たってまずは自己紹介をしたいと思います。
output: 
  blogdown::html_page:
    number_sections: false
    toc: true
    df_print: "paged"
---

どうもはじめまして。
東京にある資産運用会社に勤める新卒1年目の葦原彩人と申します。
 
簡単に自己紹介をしたいと思います。
大学院卒の24歳です。
専攻はマクロ経済学で特にDSGEモデル、状態空間モデル、カルマンフィルタ、ベイズ推定、MCMCなんかをやっていました。
指導教官の研究サポートとして自然言語処理をやったこともあります。
もともと学者志望でしたが金銭的な問題で就職することになりました。
今は営業サポートの下働きをしています。
 
このブログは研究への興味関心を捨てることができない私が趣味として研究を進めていく際の備忘録という位置付けになるのだと思います。
 
現在進めている研究は以下の２つです。  

1. 馬券版ファクターモデル
2. 四半期GDP予測モデル
 
1は、馬券市場が株式市場よりも投機的に魅力のある市場であるという観点から、回収率100%超えを目指す馬券ポートフォリオを構築するモデルを作成できないかというものです。株式にはファーマフレンチのようなファクターモデルがありますが、それを応用して馬券版ファクターモデルなるものを作れないかと思っています。
 
2は最近の四半期GDP速報の精度が低いという問題意識から、精度の高い予測モデルを新たに構築できないかというものです。特にこれまでのようなマクロ経済理論に基づいたモデルではなく、機械学習を用い、通常マクロ経済学の研究で使用しないようなデータを織り込んだモデルを作成する方向で研究を進めていきたいと思っています。
 
まだ、研究は始めたばかりなのですが、
興味を持ってもらえるように頑張りたいと思います…
では、最初はこの辺で。
 
よろしくお願いします。
