---
title: "転職します"
author: admin
date: 2020-11-08T00:00:00Z
categories: ["キャリア"]
tags: []
draft: false
featured: false
slug: ["career"]
image:
  caption: ''
  focal_point: ""
  placement: 2
  preview_only: false
lastmod: ""
projects: []
summary: 今後に関するご報告です。
subtitle:
output: 
  blogdown::html_page:
    number_sections: false
    toc: true
---

## 1. 退職しました

おはこんばんにちは。かなり久しぶりの更新になってしまいました。この間、2021年7月7日に結婚し、既婚者になりました。また、2021年4月に同じ部署内のチームを移動し、BPR・業務インフラ整備・金融規制対応などロジ周りの企画に役割が変わりました。そして、2022年2月28日に現職を退社し(最終出社は1月28日)、3月1日から関西の電子部品メーカーで働くことになりました。

## 2. 転職理由

### 入社してエコノミストが求められていないことに気づいた

そもそも、現職の資産運用会社にはエコノミストを志望して入社しました。金銭的問題から博士課程後期の進学を断念し、大学院時代の研究内容に近い職種に就きたかったためです。バイサイドのエコノミストを志望したのは、単にファンドマネージャー相手の方が高度な分析をしても許されるんじゃないかという短絡的な理由からでした。

しかし、入社してみると、希望の部署に配属になることは出来ませんでした。最初は機関投資家営業に配属になり、機関投資家向け(年金基金や金融法人)の顧客報告書をひたすら作成していました。社内DBから取得したファンドのパフォーマンスや残高を定められたフォーマットに転記し、ファンドマネージャーにコメントをもらう仕事です。2部署目(3年目)で運用企画に異動になりましたが、こちらでも(社内)資料を作成していました。企画の議論は秘匿性が高く基本的にシニア層のみで行われるため、若手は目的もはっきりとしないまま(ざっくりとした説明はありますが詳細は聞けない)、手を動かすことが求められていました。このように、資料作成要員として3年ほど過ごし、自分の成長として感じられたのは、ExcelやPowerPointに習熟していくことのみでした。次第に「市場価値など全くない人材になってるな」と危機感を覚えましたが、上司からは「まだ若いんだから」と真面目に受け止めてもらえませんでした。

同時に、エコノミストの言動を参考にしているファンドマネージャーなどほぼ存在しないことも分かりました。エコノミストの付加価値はセミナーでの講演で、その講演でも自分で分析した内容を話すと言うよりはシンクタンクなどのレポートを要約して資料を再構成し、説明するという非生産的な仕事をしているようでした。自分の就職活動時の短絡的な発想を反省しつつ、「やはりマクロ経済学ではお金にならないんだな」ということを再確認しました。

### 転職理由の半分は結婚

先述の通り、2021年7月7日に結婚しました。妻とは大学生以来の付き合いであり、7年の交際期間がありました。どちらも地元が関西であり、子供には関西弁をしゃべらせたいという最大の目的から今後を考えて生活拠点を東京から関西に移したいと思うようになりました(他にもお互いの身寄りがいるとか理由はあります)。その時点では、エコノミスト志望でもなかったので、「もはや東京にいる意味もないな」と感じていました。

2021年4月から配属になった新しい部署では、プロジェクトマネジメントを行う立場になり、ノウハウもない中で業務コンサルのような業務を行っていました。コンサル会社であるケンブリッジの書籍などを読みあさり、トライアンドエラーを繰り返す中で、プロジェクトが前進することに達成感を感じ、現場の方からの信頼も次第に得ることができました。自分たちの考えた企画案が具現化していくことにやりがいを感じ、「この仕事だったら業種も選ばないし、関西でも働けるな」と転職を考え出したのが8月頃でした。

### 残りの半分は現職でのキャリアパスが想像できなかったから

生活拠点を関西に移し、プロマネとして働くのは、現職でも遠隔地勤務という勤務形態を利用すれば可能でした。現に、同じ部署にその制度を利用している方がいたし、少なくとも2年はほぼリモートワークだったので、うちの部署なら可能だろうなというイメージも湧いていました。その選択をしなかったのは、現職ではこの職種でキャリアパスを歩んでいく事が想像できなかったからです。

資産運用会社の花形はファンドマネージャーです。新卒入社の大半がファンドマネージャー志望で入社します。業界内で有名な方も複数存在し、運用者のキャリアパスはそれなりにイメージできると思います[^1]。一方で、運用者以外のキャリアパスとなると、かなり不明瞭で各分野でプロフェッショナルとして仕事をしている方は限定的である印象を受けました。私が所属していた部署は、若手にとっては運用への通過点という位置づけで、この部署でのキャリアパスをイメージ出来る人は上司含めて存在していなかったと思います。部署にノウハウの蓄積がされておらず、シニアの仕事の進め方に疑問を抱くこともしばしばあり、目指したいと思える人物も存在しませんでした[^2]。部署柄、他の部署の方と仕事をする機会も多かったですが、状況は他の部署でも同じようで、運用者志望ではなく社内コンサル業を志望する自分にとっては、周りの支援・理解なく1人前になる想像ができず、「転職するなら早いほうがよいな」と思いました[^3]。

[^1]: アシスタント→アナリスト→FMやオペレーション担当→投資判断者などでしょうか

[^2]: 会議のファシリテーションにはかなり悩んでいました。本当であれば、会議が終わった後に細かいフィードバックを頂きたかったし、自分の課題はどこにあるのか指摘して頂きたかったですが、そのようなことが出来る人がいませんでした。「今のやり方のまま仕事を進めてくれたらいいから」しか言われなかった。

運用者志望の希望が全員叶うわけではなく、若手の早期退職者に悩む人事は多いと思いますが、一方で運用者以外の受け皿が用意されているとは言い難いと思います。少なくとも、フロントとそれ以外では温度感が全く違います(後者はシニアまでほぼオペレーション担当の印象でした)。運用会社には金融専門職(ファンドマネージャー、エコノミスト、アナリスト)はいても、ビジネスパーソンはいない。この問題は根が深いですね。

## 3. 次の会社・仕事

上記のような理由から、9月頃に転職活動をはじめました。複数のエージェントサービスを利用し、書類審査を本格的に出し始めたのが10月初旬ごろ、面接を受け出したのが10月半ばでした。そして、11月に内定を頂き、次の会社へ入社を決めました。この会社では、自部署でのキャリアステップの典型例を示してくださり、その中に自分の目指したいものがあったので入社を決めました。

次の会社は関西の電子部品メーカーです。業務内容は現職で行っている業務とさほど変わらないものと認識しています。ただ、現職よりもデータを起点にした企画を行うということで、BIツールや統計処理なども守備範囲に入ってきそうです。これまでは必要な材料は現場へのヒアリングのみをベースとしており、Excelをこねくり回して出た信頼性がわからない結果をPowerPointスライドにするというやり方だったので、ひとつステップアップかなと思います。また、扱うデータも売上情報や受注情報などこれまでの金融時系列データとは異なってきそうです。ただ、ビジネスへの深い理解が必要という点は変わらないと思うので、その点は早くキャッチアップできるように頑張りたいと思います。

## 4. 今後のブログ更新について

これまでの投稿は金融・経済に関連するものでしたが、今後は可視化・プロジェクトマネジメントなどに内容が移ってきそうです。これまでよりも、気軽に投稿することは増えてくると思うので、更新頻度を上げていきたいと思います！

